# Central variables for Path Header Scanner Make workflows.

APP_NAME := path-header-scanner
DISPLAY_NAME := Path Header Scanner
PROJECT_PACKAGE := app

SOURCE_APP := app
SOURCE_TESTS := tests
SOURCE_DIRS := $(SOURCE_APP) $(SOURCE_TESTS)

# Shared target defaults used by published utility images.
TARGET ?= app
PHS_SCAN_TARGETS ?= app docs tests

WORKSPACE_DIR ?= /workspace
SHELL_BIN ?= sh

# Platform and Python environment.
ifeq ($(OS),Windows_NT)
	PLATFORM := windows
	PYTHON_SYSTEM ?= python
	VENV_BIN_DIR := Scripts
	PYTHON_EXECUTABLE := python.exe
	PIP_EXECUTABLE := pip.exe
	VENV_ACTIVATE := activate.bat
	VENV_ACTIVATE_PS := Activate.ps1
	NULL_DEVICE := nul
	ECHO_BLANK := echo.
	PYTHON_UTF8_PREFIX := set PYTHONUTF8=1&&
else
	PLATFORM := unix
	PYTHON_SYSTEM ?= python3
	VENV_BIN_DIR := bin
	PYTHON_EXECUTABLE := python
	PIP_EXECUTABLE := pip
	VENV_ACTIVATE := activate
	NULL_DEVICE := /dev/null
	ECHO_BLANK := echo
	PYTHON_UTF8_PREFIX := PYTHONUTF8=1
endif

VENV_NAME ?= venv
VENV_DIR := $(ROOT_DIR)/$(VENV_NAME)
VENV_BIN := $(VENV_DIR)/$(VENV_BIN_DIR)
PYTHON := $(VENV_BIN)/$(PYTHON_EXECUTABLE)
PIP := $(VENV_BIN)/$(PIP_EXECUTABLE)

ifeq ($(PLATFORM),windows)
	ACTIVATE_COMMAND := $(VENV_BIN)/$(VENV_ACTIVATE)
	ACTIVATE_COMMAND_PS := $(VENV_BIN)/$(VENV_ACTIVATE_PS)
else
	ACTIVATE_COMMAND := source $(VENV_BIN)/$(VENV_ACTIVATE)
endif

REQUIREMENTS_EXCLUDE_PREFIXES := -e

# Python tools are invoked with python -m so an activated shell is optional.
PYTEST := pytest
RUFF := ruff
BLACK := black
MKDOCS := mkdocs
TWINE := twine
BUILD := build
PRE_COMMIT := pre_commit

LOCAL_RUN ?= $(PYTHON_UTF8_PREFIX) "$(PYTHON)" -m app

# Shared Path Header Scanner CLI arguments.
PHS_GLOBAL_ARGS ?=
PHS_EXTRA_ARGS ?=
PHS_INIT_ARGS ?=
PHS_SCAN_ARGS ?=

LOCAL_PHS_GLOBAL_ARGS ?= $(PHS_GLOBAL_ARGS)
LOCAL_PHS_EXTRA_ARGS ?= $(PHS_EXTRA_ARGS)
LOCAL_PHS_INIT_ARGS ?= $(PHS_INIT_ARGS)
LOCAL_PHS_SCAN_ARGS ?= $(PHS_SCAN_ARGS)

# Docker image and runtime configuration.
DOCKER ?= docker
DOCKER_COMPOSE ?= $(DOCKER) compose
DOCKER_TAG ?= latest
DOCKER_REPOSITORY ?= path-header-scanner
DOCKER_IMAGE_BASE ?= $(DOCKER_REPOSITORY)-base:$(DOCKER_TAG)
DOCKER_IMAGE_DEV ?= $(DOCKER_REPOSITORY)-dev:$(DOCKER_TAG)
DOCKER_IMAGE_PROD ?= $(DOCKER_REPOSITORY)-prod:$(DOCKER_TAG)
DOCKERFILE_BASE ?= Dockerfile
DOCKER_TTY ?= -it

DOCKER_RUN := $(DOCKER) run --rm
DOCKER_RUNTIME_ARGS ?=
DOCKER_RUN_INTERACTIVE := $(DOCKER_RUN) $(DOCKER_TTY) $(DOCKER_RUNTIME_ARGS)
DOCKER_RUN_NO_ENTRYPOINT := $(DOCKER_RUN) $(DOCKER_RUNTIME_ARGS) --entrypoint ""
DOCKER_WORKSPACE_HOST ?= $(ROOT_DIR)
DOCKER_WORKSPACE := -w $(WORKSPACE_DIR) -v "$(DOCKER_WORKSPACE_HOST):$(WORKSPACE_DIR)"
DOCKER_SOCKET ?= /var/run/docker.sock
DOCKER_SOCKET_MOUNT := -v "$(DOCKER_SOCKET):$(DOCKER_SOCKET)"

# Optional external Custy credential mount. The switch is disabled by default
# so manual Git prompts, SSH, and native helpers retain their existing behavior.
CUSTY_CREDENTIALS_MOUNT ?= false
CUSTY_CREDENTIALS_CONTAINER_DIR ?= /run/secrets/custy
CUSTY_CREDENTIALS_REMOTE ?= origin

ifeq ($(PLATFORM),windows)
CUSTY_CREDENTIALS_HOST_DIR ?= $(if $(strip $(LOCALAPPDATA)),$(LOCALAPPDATA)/Custy/credentials,$(error LOCALAPPDATA is unavailable; set CUSTY_CREDENTIALS_HOST_DIR explicitly))
else
CUSTY_CREDENTIALS_HOST_DIR ?= $(if $(strip $(XDG_DATA_HOME)),$(XDG_DATA_HOME)/custy/credentials,$(if $(strip $(HOME)),$(HOME)/.local/share/custy/credentials,$(error HOME and XDG_DATA_HOME are unavailable; set CUSTY_CREDENTIALS_HOST_DIR explicitly)))
endif

CUSTY_CREDENTIALS_RO_VOLUME = -v "$(CUSTY_CREDENTIALS_HOST_DIR):$(CUSTY_CREDENTIALS_CONTAINER_DIR):ro"
CUSTY_CREDENTIALS_RW_VOLUME = -v "$(CUSTY_CREDENTIALS_HOST_DIR):$(CUSTY_CREDENTIALS_CONTAINER_DIR)"

ifeq ($(strip $(CUSTY_CREDENTIALS_MOUNT)),true)
CUSTY_CREDENTIALS_RUNTIME_VOLUME = $(CUSTY_CREDENTIALS_RO_VOLUME)
else ifeq ($(strip $(CUSTY_CREDENTIALS_MOUNT)),false)
CUSTY_CREDENTIALS_RUNTIME_VOLUME =
else
$(error CUSTY_CREDENTIALS_MOUNT must be true or false)
endif

DOCKER_PHS_GLOBAL_ARGS ?= $(PHS_GLOBAL_ARGS)
DOCKER_PHS_EXTRA_ARGS ?= $(PHS_EXTRA_ARGS)
DOCKER_PHS_INIT_ARGS ?= $(PHS_INIT_ARGS)
DOCKER_PHS_SCAN_ARGS ?= $(PHS_SCAN_ARGS)

# Docker Compose configuration.
COMPOSE_FILE_BASE ?= docker-compose.yml
COMPOSE_FILE_DEV ?= docker-compose.dev.yml
COMPOSE_FILE_PROD ?= docker-compose.prod.yml
COMPOSE_BASE := $(DOCKER_COMPOSE) -f $(COMPOSE_FILE_BASE)
COMPOSE_DEV := $(DOCKER_COMPOSE) -f $(COMPOSE_FILE_BASE) -f $(COMPOSE_FILE_DEV)
COMPOSE_PROD := $(DOCKER_COMPOSE) -f $(COMPOSE_FILE_BASE) -f $(COMPOSE_FILE_PROD)

SERVICE_APP ?= app
SERVICE_TEST ?= test
SERVICE_LINT ?= lint
SERVICE_LINT_FIX ?= lint-fix
SERVICE_FORMAT ?= format
SERVICE_FORMAT_CHECK ?= format-check
SERVICE_DOCS ?= docs
SERVICE_SHELL ?= shell
SERVICE_BUILD ?= build

COMPOSE_DEV_RUN := $(COMPOSE_DEV) run --rm
COMPOSE_DEV_UP := $(COMPOSE_DEV) up
COMPOSE_DEV_EXEC := $(COMPOSE_DEV) exec
COMPOSE_PROD_RUN := $(COMPOSE_PROD) run --rm
COMPOSE_PROD_RUN_APP := $(COMPOSE_PROD_RUN) $(SERVICE_APP)

COMPOSE_DEV_RUN_TEST := $(COMPOSE_DEV_RUN) $(SERVICE_TEST)
COMPOSE_DEV_RUN_LINT := $(COMPOSE_DEV_RUN) $(SERVICE_LINT)
COMPOSE_DEV_RUN_LINT_FIX := $(COMPOSE_DEV_RUN) $(SERVICE_LINT_FIX)
COMPOSE_DEV_RUN_FORMAT := $(COMPOSE_DEV_RUN) $(SERVICE_FORMAT)
COMPOSE_DEV_RUN_FORMAT_CHECK := $(COMPOSE_DEV_RUN) $(SERVICE_FORMAT_CHECK)
COMPOSE_DEV_UP_DOCS := $(COMPOSE_DEV_UP) $(SERVICE_DOCS)
COMPOSE_DEV_RUN_SHELL := $(COMPOSE_DEV_RUN) $(SERVICE_SHELL)
COMPOSE_DEV_RUN_BUILD := $(COMPOSE_DEV_RUN) $(SERVICE_BUILD)

COMPOSE_PHS_GLOBAL_ARGS ?= $(PHS_GLOBAL_ARGS)
COMPOSE_PHS_EXTRA_ARGS ?= $(PHS_EXTRA_ARGS)
COMPOSE_PHS_INIT_ARGS ?= $(PHS_INIT_ARGS)
COMPOSE_PHS_SCAN_ARGS ?= $(PHS_SCAN_ARGS)

# Published container configuration.
GHCR_REGISTRY ?= ghcr.io
GHCR_OWNER ?= devalltect00
REMOTE_IMAGE_PHS ?= path-header-scanner
REMOTE_IMAGE_DOC_GEN ?= doc-gen
REMOTE_IMAGE_CUSTY ?= custy
REMOTE_IMAGE_REFLOW ?= reflow
REMOTE_TAG ?= latest
REMOTE_WORKSPACE ?= $(ROOT_DIR)
DOCKER_REMOTE_WORKSPACE := -w $(WORKSPACE_DIR) -v "$(REMOTE_WORKSPACE):$(WORKSPACE_DIR)"

# Path Header Scanner published-image arguments.
REMOTE_PHS_GLOBAL_ARGS ?=
REMOTE_PHS_EXTRA_ARGS ?=
REMOTE_PHS_INIT_ARGS ?=
REMOTE_PHS_SCAN_ARGS ?=

# Doc Gen published-image arguments.
REMOTE_DOC_GEN_GLOBAL_ARGS ?=
REMOTE_DOC_GEN_EXTRA_ARGS ?=
REMOTE_DOC_GEN_INIT_ARGS ?=
REMOTE_DOC_GEN_STRUCTURE_ARGS ?=
REMOTE_DOC_GEN_GENERATE_ARGS ?=
REMOTE_DOC_GEN_PRINT_ARGS ?=
REMOTE_DOC_GEN_ANALYZE_ARGS ?=

# Custy published-image arguments.
REMOTE_CUSTY_GLOBAL_ARGS ?=
REMOTE_CUSTY_EXTRA_ARGS ?=
REMOTE_CUSTY_INIT_ARGS ?=
REMOTE_CUSTY_VALIDATE_ARGS ?=
REMOTE_CUSTY_VERSION_ARGS ?=
REMOTE_CUSTY_CHANGELOG_ARGS ?=
REMOTE_CUSTY_COMMIT_ARGS ?=
REMOTE_CUSTY_TAG_ARGS ?=
REMOTE_CUSTY_PUSH_ARGS ?=
REMOTE_CUSTY_RUN_ARGS ?=
REMOTE_CUSTY_RUN_SUBCOMMAND ?=
REMOTE_CUSTY_RUN_SUBCOMMAND_ARGS ?=
REMOTE_CUSTY_RUN_DEV_ARGS ?=
REMOTE_CUSTY_RUN_RELEASE_ARGS ?=
REMOTE_CUSTY_RUN_FULL_ARGS ?=
REMOTE_CUSTY_BACKUP_ARGS ?=
REMOTE_CUSTY_BACKUP_COMMIT_ARGS ?=
REMOTE_CUSTY_BACKUP_TAG_ARGS ?=
REMOTE_CUSTY_BACKUP_ALL_ARGS ?=
REMOTE_CUSTY_CLEANUP_ARGS ?=
REMOTE_CUSTY_CLEANUP_BACKUPS_ARGS ?=
REMOTE_CUSTY_CLEANUP_BRANCHES_ARGS ?=
REMOTE_CUSTY_CLEANUP_ALL_ARGS ?=
REMOTE_CUSTY_WORKFLOW_ARGS ?=

# Reflow published-image arguments.
REMOTE_REFLOW_GLOBAL_ARGS ?=
REMOTE_REFLOW_EXTRA_ARGS ?=
REMOTE_REFLOW_INIT_ARGS ?=
REMOTE_REFLOW_RELEASES_RECOVER_ARGS ?=
REMOTE_REFLOW_TAGS_CONVERT_ARGS ?=
REMOTE_REFLOW_DOCKERIZE_ARGS ?=
